#!/bin/bash
set -e


sudo find /etc/apt -name "*kubernetes*" -type f -exec rm -f {} \;
sudo find /etc/apt -name "*k8s*" -type f -exec rm -f {} \;

sudo rm -rf /etc/apt/keyrings/*
sudo apt-get clean
sudo apt-get update

echo "STEP 1: Disable swap"
swapoff -a
sed -i '/ swap / s/^/#/' /etc/fstab

echo "STEP 2: Kernel config"
modprobe overlay
modprobe br_netfilter

cat <<EOF > /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables=1
net.bridge.bridge-nf-call-ip6tables=1
net.ipv4.ip_forward=1
EOF

sysctl --system

echo "STEP 3: Install containerd"
apt-get update
apt-get install -y containerd

mkdir -p /etc/containerd
containerd config default > /etc/containerd/config.toml

sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml

systemctl restart containerd
systemctl enable containerd

echo "STEP 4: Install Kubernetes repo"
mkdir -p /etc/apt/keyrings

curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | \
gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg

echo "deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] \
https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" \
> /etc/apt/sources.list.d/kubernetes.list

apt-get update

echo "STEP 5: Install Kubernetes"
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl

echo "STEP 6: Init cluster"
kubeadm init \
--pod-network-cidr=192.168.0.0/16 \
--cri-socket=unix:///run/containerd/containerd.sock

echo "STEP 7: Setup kubectl"
mkdir -p $HOME/.kube
cp /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config

export KUBECONFIG=$HOME/.kube/config

echo "STEP 8: Network"
kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

kubectl taint nodes --all node-role.kubernetes.io/control-plane- || true

echo "DONE"
