CREATE OR REPLACE DATABASE TRAINING_DB;

USE DATABASE TRAINING_DB;

CREATE OR REPLACE SCHEMA DEMO;

USE SCHEMA DEMO;

CREATE OR REPLACE WAREHOUSE TRAINING_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;



CREATE OR REPLACE TABLE CUSTOMERS
(
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME STRING,
    CITY STRING,
    STATE STRING
);



CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE=CSV
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY='"';



CREATE OR REPLACE STORAGE INTEGRATION ADLS_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = AZURE
ENABLED = TRUE
AZURE_TENANT_ID = 'feb2284d-7df4-42a0-a4de-94be9432972d'
STORAGE_ALLOWED_LOCATIONS =
(
'azure://adlstrainingdemo12345.blob.core.windows.net/training'
);



DESC INTEGRATION ADLS_INT;

CREATE OR REPLACE STAGE ADLS_STAGE
URL='azure://adlstrainingdemo12345.blob.core.windows.net/training/input'
STORAGE_INTEGRATION = ADLS_INT
FILE_FORMAT = CSV_FORMAT;


DESC STAGE ADLS_STAGE;


LIST @ADLS_STAGE;



CREATE OR REPLACE NOTIFICATION INTEGRATION AZURE_QUEUE_INT
TYPE = QUEUE
ENABLED = TRUE
NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
AZURE_STORAGE_QUEUE_PRIMARY_URI ='https://adlstrainingdemo12345.queue.core.windows.net/snowpipequeue'
AZURE_TENANT_ID = 'feb2284d-7df4-42a0-a4de-94be9432972d';



DESC NOTIFICATION INTEGRATION AZURE_QUEUE_INT;


CREATE OR REPLACE PIPE CUSTOMER_PIPE
AUTO_INGEST = TRUE
INTEGRATION = 'AZURE_QUEUE_INT'
AS
COPY INTO CUSTOMERS
FROM @ADLS_STAGE
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);



SHOW PIPES;


SELECT SYSTEM$PIPE_STATUS('CUSTOMER_PIPE');



SELECT * FROM CUSTOMERS;
