name: CI/CD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'





